#define the services/containers for this app
services:
  app:
    #use the build instruction to tell Docker Compose to build the image from DockerFile
    build:
      context: .
    ports:
      - "8090:8090"
    restart: unless-stopped
    env_file:
      - .env